### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by shalonwalter** [INFO526-DataViz/project-final-Graph-Gurus#1]
The following is the peer review of the project proposal by Plot Pioneers. 
The team members that participated in this review are 

Athira Thekkemdathil Anilkumar - @AthiraThekkemadathilAnilkumar

Priyarsha Vallabhaneni - @Priyarsha31

Shalon Walter - @shalonwalter

Chethana Thondebhavi Shantha Kumar - @Chethana-16

- Describe the goal of the project.

The project aims to develop an Interactive Drought Dashboard for analyzing Arizona's drought conditions from 2000 to the present. This tool will enable users to examine drought trends and data across specific time frames or counties.

- Describe the data used or collected.

The data utilized for this project is the Arizona Drought Conditions Dataset, which offers insights into short-term and long-term drought conditions across Arizona counties from the year 2000 to the present. This dataset is maintained and updated by the Arizona Drought Monitoring Technical Committee.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The goal is to provide interactive data visualizations using R programming and libraries such as Shiny, Leaflet, and ggplot2. The team will create maps, time series plots, and statistical charts to provide insights into the drought conditions.

- Is there anything that is unclear from the proposal?

The proposal could clarify the high-level goals, motivation and reason for choosing this specific dataset. Additionally, it should detail the final organization of the project repository.

- Provide constructive feedback on how the team might be able to improve their project.

Consider integrating the "Did You Know?" section with the introduction for better flow.

The package setup code can be removed to improve the aesthetic of the document.

Provide direct web sources for the dataset, if available, for credibility and transparency.

Although a research question isn't compulsory, your project should still aim to address specific queries. While you've outlined a goal, supplementing it with targeted questions that relate to this goal would enhance the project's aim. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The geographic visualization component is intriguing. Highlighting how different areas within Arizona are affected differently by drought conditions could be particularly impactful.

- Provide constructive feedback on any issues with file and/or code organization.

While the proposal does not cover file and code organization, ensuring a structured and well-documented repository will be crucial for maintaining the project.

- (Optional) Any further comments or feedback?

The project is commendably focused on a relevant environmental issue with a well-thought-out aim. The use of a large and comprehensive dataset promises detailed insights, and the interactive dashboard could effectively raise awareness and prompt action on water scarcity. - All the best, Plot pioneers.

**Comment by AkrantVarshney** [comment]
Thank you for the valuable feedback. We've incorporated the suggested improvements into our proposal, and we're eagerly anticipating the opportunity to showcase the final outcome of our project.

 Thank you for the constructive feedback and good luck.
