### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by bharath03-a** [INFO526-DataViz/project-final-Graph-Gurus#2]
The following is the peer review of the project proposal by Infographic Innovators. The team members that participated in this review are 

Eshaan Mathakari: @eshaanmathakari

Bharath Velamala: @bharath03-a

Thanoosha Naidu Karri: @thanooshakarri

Antonio Escalante Jr: @datalyticsintel

- Describe the goal of the project.
The goal of the project is clearly outlined, aiming to develop an Interactive Drought Dashboard for Arizona. The objective is to provide a detailed view of Arizona's drought conditions from 2000 to the present using a dashboard.

- Describe the data used or collected.
The data used by the team is sourced from Arizona Drought Monitoring Technical Committee. This dataset provides important insights on the drought conditions in the state of Arizona. There are no missing values present in the dataset. The dataset gives information related to different drought conditions which will be beneficial in identifying the drought counties as they suggested.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The proposal lacks a specific research question and detailed approaches/methods to answer it. It would be beneficial to include the research question(s) that the team aims to address for the analysis. Providing this information would enhance the overall project plan.
Based on the given plots and it's inference we can understand that they are going to focus on geographic visualization, time series analysis on drought levels and provide some statistical insights.

- Is there anything that is unclear from the proposal?
No clarity about the questions they are trying to propose or resolve from their projects. Missing approach to their problems.
It was unclear on who they are going to plot a map plot with the given data.

- Provide constructive feedback on how the team might be able to improve their project.
They can start by rendering and deploying their website. 
Data directory/ Repo organization related information is missing.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are excited to see the time series visualization of the drought and how it has changed and worsened. They said their aim was to show the drought to get people thinking, maybe they can also provide some examples of how people should move forward when dealing with a drought. 

- Provide constructive feedback on any issues with file and/or code organization.
Render and deploy the website as we had to do it manually. Otherwise, they had the data read in properly.

- (Optional) Any further comments or feedback?

Looking forward to your presentation!

**Comment by SwethaSiripurapuu** [comment]
Hello Team, Thank you for the feedback. We have carefully reviewed your suggestions and have updated our proposal accordingly. We are sorry that you had to render the website manually. 

Additionally, we'd like to address a particular point: while we understand the importance of a clearly defined research question in adding more structure to the proposal, we believe that our project's goal is sufficiently robust to guide our efforts. We are really excited to create some amazing visualizations with this data. We really appreciate and value your feedback. Thank you and good luck :)
