### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-final-Graph-Gurus#3]
Dear Graph Gurus: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

Your final score is **9.5/10** (between your two scores 9 and 10) 

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |       3 |
| Proposal | 5         |       4 |
| Workflow | 1         |        1|
| Teamwork | 1         |      1  |
| Total    | 10        |     9   |

Proposal: Your goal should be at the top, it informs the importance of the proposal. Its worth also having a few concrete goals as well in bullets below this. 
Overall: Good work, I'm impressed with the relevance and the project in general!

**Comment by marianikitha01** [comment]
Placed Goals at the top and added more bullet points, closes #3
