### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by eshaanmathakari** [INFO526-DataViz/project-final-Graph-Gurus#7]
The following is the peer review of the Presentation proposal by Infographic Innovators. The team members that participated in this review are 

Team member 1: Eshaan Mathakari: First-year graduate student in Data Science at University of Arizona., github: @eshaanmathakari

Team member 2: Bharath Velamala, First-year graduate student in Data Science at University of Arizona., github: @bharath03-a

Team member 3: Thanoosha Naidu Karri, First-year graduate student in Data Science at University of Arizona., guthub: @thanooshakarri

Team member 4: Antonio Escalante Jr, First-year graduate student in Data Science at University of Arizona., github: @datalyticsintel

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, data is being used relevantly. But the source of dataset is not defined in the presentation. No real issue, just wanted to know :).

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, visualisations were appropriate and the dashboard was good.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes, slides were done well and are legible. A lot of descriptive plots though were smaller and not legible but that's a minor issue.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Yes, everyone got to present and they did know a significant amount of the topic they were presenting about. Visualisations were well explained.

**Comment by SwethaSiripurapuu** [comment]
ThankYou!
